name: Notify Cron Workflow
on:
  schedule:
    - cron: "0 0-10/3,10-18,18-23/3 * * *"
  workflow_dispatch:
jobs:
  cron:
    environment: "Notify - cron"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: Run script
        env:
          EM_ID: ${{ secrets.EM_ID }}
          EM_PW: ${{ secrets.EM_PW }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm start
